!SESSION 2023-10-06 16:13:51.348 -----------------------------------------------
eclipse.buildId=4.15.0.2020042
java.fullversion=8.0.7.5 - pwa6480sr7fp5ifix-20220310_01(SR7 FP5+IJ37785)
JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
OpenJ9   - 2d4c7d9
OMR      - 59845b7
IBM      - 3c151c1
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_CO
Framework arguments:  -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide
Command-line arguments:  -data Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion -os win32 -ws win32 -arch x86_64 -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-06 16:13:54.282
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-06 16:13:54.282
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-06 16:13:54.282
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.pattern.capture.annotation' register a package for 'http://www.ibm.com/patternAnnotation/2010'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-06 16:13:54.282
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'org.eclipse.emf.ecore' register a package for 'http://www.eclipse.org/emf/2002/Ecore'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-06 16:13:54.297
!MESSAGE Both 'com.ibm.etools.javaee.core' and 'com.ibm.etools.mft.service.model' register an extension parser for 'application'

!ENTRY org.eclipse.ui 2 2 2023-10-06 16:13:59.569
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.adapter.c, page: com.ibm.adapter.c.ui.preferencepage.CPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-06 16:13:59.569
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.etools.cobol.preference.ui, page: com.ibm.etools.cobol.preference.ui.preferencepage.CobolPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-06 16:13:59.569
!MESSAGE Invalid preference category path: com.ibm.debug.breakpoints.common.pref.tracepoint (bundle: com.ibm.debug.wsa, page: com.ibm.debug.wsa.WSATracepointPreferencePage)

!ENTRY org.eclipse.jface.text 2 0 2023-10-06 16:14:06.266
!MESSAGE Duplicate template id: 'com.ibm.datatools.sqlxeditor.templates.xmlnamespaces2'

!ENTRY org.eclipse.egit.ui 2 0 2023-10-06 16:14:10.305
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\marco'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY com.ibm.etools.mft.pattern.community 4 0 2023-10-06 16:14:10.539
!MESSAGE Connection to the URL https://ot4i.github.io/ace-patterns/es/repo_metadata.json failed. Response code: 404

!ENTRY com.ibm.mq.runtime 1 0 2023-10-06 16:14:11.164
!MESSAGE 

!ENTRY com.ibm.mq.runtime 1 0 2023-10-06 16:14:11.164
!MESSAGE C:\Program Files\IBM\ACE\12.0.5.0\tools>mqsifindmqpath

!ENTRY com.ibm.mq.runtime 1 0 2023-10-06 16:14:12.890
!MESSAGE BIP8071I: El mandato ha finalizado correctamente. C:\Program Files\IBM\MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-06 16:14:12.890
!MESSAGE MQ Install location found:C:/Program Files/IBM/MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-06 16:14:12.890
!MESSAGE 

!ENTRY org.eclipse.core.resources 4 567 2023-10-06 17:15:20.133
!MESSAGE Failure occurred reading .project file.
!SUBENTRY 1 org.eclipse.core.resources 4 567 2023-10-06 17:15:20.133
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$571/0x000000003d98ba70.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.core.resources 2 567 2023-10-06 17:15:20.133
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$571/0x000000003d98ba70.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.eclipse.core.resources 4 567 2023-10-06 17:15:20.229
!MESSAGE Failure occurred reading .project file.
!SUBENTRY 1 org.eclipse.core.resources 4 567 2023-10-06 17:15:20.229
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$571/0x000000003d98ba70.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.core.resources 2 567 2023-10-06 17:15:20.229
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$571/0x000000003d98ba70.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY com.ibm.etools.mft.uri 0 0 2023-10-06 17:21:03.996
!MESSAGE 

!ENTRY org.eclipse.ui 4 0 2023-10-06 17:21:46.151
!MESSAGE Unable to store working set state.
!STACK 0
java.io.FileNotFoundException: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\org.eclipse.ui.workbench\workingsets.xml (The process cannot access the file because it is being used by another process.)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:286)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:173)
	at org.eclipse.ui.internal.AbstractWorkingSetManager.saveState(AbstractWorkingSetManager.java:781)
	at org.eclipse.ui.internal.WorkingSetManager.saveState(WorkingSetManager.java:137)
	at org.eclipse.ui.internal.WorkingSetManager.addWorkingSet(WorkingSetManager.java:67)
	at com.ibm.etools.mft.navigator.workingsets.BrokerWorkingSetUtils.addBrokerWorkingSet(BrokerWorkingSetUtils.java:640)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.recalculateWorkingSetContent(ProjectFileChangeListener.java:183)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.doIt(ProjectFileChangeListener.java:58)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.resourceChanged(ProjectFileChangeListener.java:41)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:380)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2306)
	at org.eclipse.core.internal.events.NotificationManager$NotifyJob.run(NotificationManager.java:44)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:05.172
!MESSAGE Link indexer shutdown-0 [EXCEPTION] Error during write back, record: 35 file Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db
!STACK 0
java.lang.RuntimeException: com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during write (offset=1576, length=1) from file: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.runUninterruptibly(IO.java:405)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.write(IO.java:193)
	at com.ibm.etools.references.internal.bplustree.db.Extent.writeRecords(Extent.java:599)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.performUpdate(ExtentManager.java:1334)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.realUpdate(ExtentManager.java:1160)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager$WriteBack.run(ExtentManager.java:524)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager$WriteBack.executeNow(ExtentManager.java:345)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.joinPendingWrites(ExtentManager.java:2145)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.joinPendingWrites(ReferenceDatabase.java:729)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:737)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during write (offset=1576, length=1) from file: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.doWrite(IO.java:225)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO$1.call(IO.java:197)
	at com.ibm.etools.references.internal.ThreadSupport$ScheduledFutureTask$CallableWrapper.call(ThreadSupport.java:229)
	... 5 more
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:87)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:105)
	at sun.nio.ch.IOUtil.write(IOUtil.java:77)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:223)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.doWrite(IO.java:218)
	... 7 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.194
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:752)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 11 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.200
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_TARGETPATH-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.203
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_TARGETLINKID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.234
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCELINKID-REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.237
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKTEXT-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.242
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKNAME-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.245
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_MODELINSTANCEID_REF-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.248
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCEPATH-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.251
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCELINKID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.280
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_REFERENCETYPE-REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.283
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\LINK-BY_SOURCEPATH-BY_LINKTYPE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.286
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_REFERENCE_ID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.289
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKTYPE-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.378
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCEPATH-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.382
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\string.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.index.StringDatabase.shutdown(StringDatabase.java:588)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:771)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 12 more

!ENTRY com.ibm.etools.references 4 0 2023-10-09 10:38:07.384
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Worksapace.Facturacion\.metadata\.plugins\com.ibm.etools.references\refDB\string.idx.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.StringDatabase.shutdown(StringDatabase.java:589)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:771)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more
