!SESSION 2023-10-10 11:37:52.817 -----------------------------------------------
eclipse.buildId=4.15.0.2020042
java.fullversion=8.0.7.5 - pwa6480sr7fp5ifix-20220310_01(SR7 FP5+IJ37785)
JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
OpenJ9   - 2d4c7d9
OMR      - 59845b7
IBM      - 3c151c1
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_CO
Framework arguments:  -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-10 11:38:06.411
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-10 11:38:06.446
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-10 11:38:06.446
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.pattern.capture.annotation' register a package for 'http://www.ibm.com/patternAnnotation/2010'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-10 11:38:06.452
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'org.eclipse.emf.ecore' register a package for 'http://www.eclipse.org/emf/2002/Ecore'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-10 11:38:06.458
!MESSAGE Both 'com.ibm.etools.javaee.core' and 'com.ibm.etools.mft.service.model' register an extension parser for 'application'

!ENTRY org.eclipse.ui 2 2 2023-10-10 11:38:29.209
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.adapter.c, page: com.ibm.adapter.c.ui.preferencepage.CPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-10 11:38:29.209
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.etools.cobol.preference.ui, page: com.ibm.etools.cobol.preference.ui.preferencepage.CobolPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-10 11:38:29.248
!MESSAGE Invalid preference category path: com.ibm.debug.breakpoints.common.pref.tracepoint (bundle: com.ibm.debug.wsa, page: com.ibm.debug.wsa.WSATracepointPreferencePage)

!ENTRY org.eclipse.jface.text 2 0 2023-10-10 11:38:42.687
!MESSAGE Duplicate template id: 'com.ibm.datatools.sqlxeditor.templates.xmlnamespaces2'

!ENTRY org.eclipse.egit.ui 2 0 2023-10-10 11:38:47.536
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\marco'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY com.ibm.etools.mft.pattern.community 4 0 2023-10-10 11:38:51.325
!MESSAGE Connection to the URL https://ot4i.github.io/ace-patterns/es/repo_metadata.json failed. Response code: 404

!ENTRY com.ibm.mq.runtime 1 0 2023-10-10 11:38:52.723
!MESSAGE 

!ENTRY com.ibm.mq.runtime 1 0 2023-10-10 11:38:52.723
!MESSAGE C:\Program Files\IBM\ACE\12.0.5.0\tools>mqsifindmqpath

!ENTRY com.ibm.mq.runtime 1 0 2023-10-10 11:38:54.739
!MESSAGE BIP8071I: El mandato ha finalizado correctamente. C:\Program Files\IBM\MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-10 11:38:54.739
!MESSAGE MQ Install location found:C:/Program Files/IBM/MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-10 11:38:54.739
!MESSAGE 

!ENTRY org.eclipse.core.resources 4 567 2023-10-10 11:41:36.786
!MESSAGE Failure occurred reading .project file.
!SUBENTRY 1 org.eclipse.core.resources 4 567 2023-10-10 11:41:36.786
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$569/0x0000000018637100.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.core.resources 2 567 2023-10-10 11:41:36.786
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$569/0x0000000018637100.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.eclipse.core.resources 4 567 2023-10-10 11:41:36.832
!MESSAGE Failure occurred reading .project file.
!SUBENTRY 1 org.eclipse.core.resources 4 567 2023-10-10 11:41:36.832
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$569/0x0000000018637100.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.core.resources 2 567 2023-10-10 11:41:36.833
!MESSAGE Fin prematuro del archivo.
!STACK 0
org.xml.sax.SAXParseException: Fin prematuro del archivo.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.core.internal.resources.ProjectDescriptionReader.read(ProjectDescriptionReader.java:930)
	at org.eclipse.core.internal.resources.Workspace.loadProjectDescription(Workspace.java:1960)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.setProjectName(WizardProjectsImportPage.java:218)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$ProjectRecord.<init>(WizardProjectsImportPage.java:193)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1178)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.collectProjectFilesFromProvider(WizardProjectsImportPage.java:1173)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.lambda$7(WizardProjectsImportPage.java:949)
	at org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage$$Lambda$569/0x0000000018637100.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY com.ibm.etools.mft.uri 0 0 2023-10-10 11:42:42.677
!MESSAGE 

!ENTRY org.eclipse.ui 4 0 2023-10-10 11:42:48.224
!MESSAGE Unable to store working set state.
!STACK 0
java.io.FileNotFoundException: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\org.eclipse.ui.workbench\workingsets.xml (The process cannot access the file because it is being used by another process.)
	at java.io.FileOutputStream.open(FileOutputStream.java:286)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:173)
	at org.eclipse.ui.internal.AbstractWorkingSetManager.saveState(AbstractWorkingSetManager.java:781)
	at org.eclipse.ui.internal.WorkingSetManager.saveState(WorkingSetManager.java:137)
	at org.eclipse.ui.internal.WorkingSetManager.addWorkingSet(WorkingSetManager.java:67)
	at com.ibm.etools.mft.navigator.workingsets.BrokerWorkingSetUtils.addBrokerWorkingSet(BrokerWorkingSetUtils.java:640)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.recalculateWorkingSetContent(ProjectFileChangeListener.java:183)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.doIt(ProjectFileChangeListener.java:58)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.resourceChanged(ProjectFileChangeListener.java:41)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:380)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2306)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.eclipse.ui 4 0 2023-10-10 11:42:48.724
!MESSAGE Unable to store working set state.
!STACK 0
java.io.FileNotFoundException: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\org.eclipse.ui.workbench\workingsets.xml (The process cannot access the file because it is being used by another process.)
	at java.io.FileOutputStream.open(FileOutputStream.java:286)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:173)
	at org.eclipse.ui.internal.AbstractWorkingSetManager.saveState(AbstractWorkingSetManager.java:781)
	at org.eclipse.ui.internal.WorkingSetManager.saveState(WorkingSetManager.java:137)
	at org.eclipse.ui.internal.WorkingSetManager.addWorkingSet(WorkingSetManager.java:67)
	at com.ibm.etools.mft.navigator.workingsets.BrokerWorkingSetUtils.addBrokerWorkingSet(BrokerWorkingSetUtils.java:640)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.recalculateWorkingSetContent(ProjectFileChangeListener.java:183)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.doIt(ProjectFileChangeListener.java:58)
	at com.ibm.etools.mft.navigator.workingsets.ProjectFileChangeListener.resourceChanged(ProjectFileChangeListener.java:41)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:380)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2306)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:31.774
!MESSAGE Link indexer shutdown-0 [EXCEPTION] Error during write back, record: 73 file Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db
!STACK 0
java.lang.RuntimeException: com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during write (offset=3248, length=1) from file: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.runUninterruptibly(IO.java:405)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.write(IO.java:193)
	at com.ibm.etools.references.internal.bplustree.db.Extent.writeRecords(Extent.java:599)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.performUpdate(ExtentManager.java:1334)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.realUpdate(ExtentManager.java:1160)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager$WriteBack.run(ExtentManager.java:524)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager$WriteBack.executeNow(ExtentManager.java:345)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.joinPendingWrites(ExtentManager.java:2145)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.joinPendingWrites(ReferenceDatabase.java:729)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:737)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during write (offset=3248, length=1) from file: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.doWrite(IO.java:225)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO$1.call(IO.java:197)
	at com.ibm.etools.references.internal.ThreadSupport$ScheduledFutureTask$CallableWrapper.call(ThreadSupport.java:229)
	... 5 more
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:87)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:105)
	at sun.nio.ch.IOUtil.write(IOUtil.java:77)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:223)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.doWrite(IO.java:218)
	... 7 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.792
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\artifact.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:752)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 11 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.792
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_TARGETPATH-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.800
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_TARGETLINKID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.800
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCELINKID-REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.800
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKTEXT-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.838
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKNAME-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.849
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_MODELINSTANCEID_REF-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.885
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCEPATH-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.894
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCELINKID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.894
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_REFERENCETYPE-REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.894
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\LINK-BY_SOURCEPATH-BY_LINKTYPE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.894
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_REFERENCE_ID-RESOLVED_REFERENCE.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.932
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_LINKTYPE-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.932
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\BY_SOURCEPATH-LINK.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.IndexManager.closeIndexes(IndexManager.java:1016)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:762)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.937
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\string.db.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.index.StringDatabase.shutdown(StringDatabase.java:588)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:771)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 12 more

!ENTRY com.ibm.etools.references 4 0 2023-10-11 10:12:33.941
!MESSAGE Exception during close of [e=0]
!STACK 0
com.ibm.etools.references.internal.bplustree.db.FatalIOException: Exception during closing  of: Z:\2.2.ProyectosAssist\4.ClinicaSantafe\ACE.Workspace.RISFundation\.metadata\.plugins\com.ibm.etools.references\refDB\string.idx.e0
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:440)
	at com.ibm.etools.references.internal.bplustree.db.Extent.close(Extent.java:808)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.doClose(ExtentManager.java:1944)
	at com.ibm.etools.references.internal.bplustree.db.ExtentManager.close(ExtentManager.java:1910)
	at com.ibm.etools.references.internal.bplustree.tree.BPTree.close(BPTree.java:540)
	at com.ibm.etools.references.internal.index.DiskBasedReferenceIndex.close(DiskBasedReferenceIndex.java:245)
	at com.ibm.etools.references.internal.index.StringDatabase.shutdown(StringDatabase.java:589)
	at com.ibm.etools.references.internal.index.ReferenceDatabase.shutdown(ReferenceDatabase.java:771)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:146)
	at com.ibm.etools.references.internal.management.InternalReferenceManager$ShutdownCode.call(InternalReferenceManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at com.ibm.etools.references.internal.ReferenceThreadFactrory$ReferencesThread.run(ReferenceThreadFactrory.java:37)
Caused by: java.io.IOException: The parameter is incorrect.
	at sun.nio.ch.FileDispatcherImpl.release0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.release(FileDispatcherImpl.java:123)
	at sun.nio.ch.FileChannelImpl.release(FileChannelImpl.java:1162)
	at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:73)
	at com.ibm.etools.references.internal.bplustree.db.IO$FileChannelIO.close(IO.java:426)
	... 14 more
!SESSION 2023-10-12 21:51:36.585 -----------------------------------------------
eclipse.buildId=4.15.0.2020042
java.fullversion=8.0.7.5 - pwa6480sr7fp5ifix-20220310_01(SR7 FP5+IJ37785)
JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
OpenJ9   - 2d4c7d9
OMR      - 59845b7
IBM      - 3c151c1
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_CO
Framework arguments:  -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -showlocation -product com.ibm.etools.msgbroker.tooling.ide tools_auto -showlocation -product com.ibm.etools.msgbroker.tooling.ide

!ENTRY org.eclipse.equinox.registry 2 0 2023-10-12 21:51:41.369
!MESSAGE The extensions and extension-points from the bundle "org.eclipse.emf.commonj.sdo" are ignored. The bundle is not marked as singleton. 

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-12 21:52:03.286
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-12 21:52:03.288
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'com.ibm.etools.mft.gef.emf' register a package for 'http://www.ibm.com/wbi/2005/eflow_utility'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-12 21:52:03.290
!MESSAGE Both 'com.ibm.etools.mft.fcb' and 'com.ibm.etools.mft.pattern.capture.annotation' register a package for 'http://www.ibm.com/patternAnnotation/2010'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-12 21:52:03.295
!MESSAGE Both 'com.ibm.etools.mft.gef.emf' and 'org.eclipse.emf.ecore' register a package for 'http://www.eclipse.org/emf/2002/Ecore'

!ENTRY org.eclipse.emf.ecore 2 0 2023-10-12 21:52:03.308
!MESSAGE Both 'com.ibm.etools.javaee.core' and 'com.ibm.etools.mft.service.model' register an extension parser for 'application'

!ENTRY org.eclipse.ui 2 2 2023-10-12 21:52:06.577
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.adapter.c, page: com.ibm.adapter.c.ui.preferencepage.CPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-12 21:52:06.579
!MESSAGE Invalid preference category path: com.ibm.importer.preferences (bundle: com.ibm.etools.cobol.preference.ui, page: com.ibm.etools.cobol.preference.ui.preferencepage.CobolPreferencePage)

!ENTRY org.eclipse.ui 2 2 2023-10-12 21:52:06.581
!MESSAGE Invalid preference category path: com.ibm.debug.breakpoints.common.pref.tracepoint (bundle: com.ibm.debug.wsa, page: com.ibm.debug.wsa.WSATracepointPreferencePage)

!ENTRY com.ibm.etools.mft.uri 0 0 2023-10-12 21:53:15.133
!MESSAGE 

!ENTRY org.eclipse.jface.text 2 0 2023-10-12 21:53:53.421
!MESSAGE Duplicate template id: 'com.ibm.datatools.sqlxeditor.templates.xmlnamespaces2'

!ENTRY com.ibm.mq.runtime 1 0 2023-10-12 21:53:54.406
!MESSAGE 

!ENTRY com.ibm.mq.runtime 1 0 2023-10-12 21:53:54.411
!MESSAGE C:\Program Files\IBM\ACE\12.0.5.0\tools>mqsifindmqpath

!ENTRY com.ibm.etools.mft.pattern.community 4 0 2023-10-12 21:53:55.007
!MESSAGE Connection to the URL https://ot4i.github.io/ace-patterns/es/repo_metadata.json failed. Response code: 404

!ENTRY com.ibm.mq.runtime 1 0 2023-10-12 21:53:55.609
!MESSAGE BIP8071I: El mandato ha finalizado correctamente. C:\Program Files\IBM\MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-12 21:53:55.614
!MESSAGE MQ Install location found:C:/Program Files/IBM/MQ

!ENTRY com.ibm.mq.runtime 1 0 2023-10-12 21:53:55.618
!MESSAGE 

!ENTRY org.eclipse.egit.ui 2 0 2023-10-12 21:53:56.147
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\marco'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
